### PR TITLE
Added playground for Info List Item

### PR DESCRIPTION
**Pull request by KomalGDhere-eaton**
Fixes # .

#### Changes proposed in this Pull Request:
-Configure the library and set up the Playground Tab in the layout
-Configure the Playground tab

#### Screenshots / Screen Recording (if applicable)

image
image

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by shubham-eaton** [comment]
@KomalGDhere-eaton  prettier is failing, can you look up into this.

**Comment by komal-eaton** [comment]
@KomalGDhere-eaton  we are not using clickable anywhere, can we remove that?

**Review by komal-eaton — APPROVED** [review]

**Comment by JeffGreiner-eaton** [comment]
This looks good, do we know why subtitleSeparator "character" isn't displaying or working?

**Comment by KomalGDhere-eaton** [comment]
> This looks good, do we know why subtitleSeparator "character" isn't displaying or working?

 subtitleSeperator working for infoListItem component but Playground not supporting this, so we have disabled this in playground.

**Comment by ArshdeepSingh3-eaton** [comment]
as of now playgrond subtitle field does not support array so the subtitle separator cannot be used
as subtitle separator only works with array passed in subtitle

**Pull request merged**
