### PR TITLE
add channel value Example

### PR DESCRIPTION
**Pull request by ArshdeepSingh3-eaton**
Fixes # .

#### Changes proposed in this Pull Request:

- Added Channel Value Example
-
-

#### Screenshots / Screen Recording (if applicable)

-
Screenshot 2024-05-29 at 3 03 42 PM

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
do we have plans to use action button row like we did here https://github.com/etn-ccis/blui-react-component-library/blob/dev/docs/src/shared/CodeBlockActionButtonRow.tsx and prism too https://github.com/etn-ccis/blui-react-component-library/blob/dev/docs/src/shared/CodeBlock.tsx

**Comment by ArshdeepSingh3-eaton** [comment]
we will have to do that later
as of now we are just creating a mdx file and nothing else

**Comment by ektaghag-eaton** [comment]
While using images can we check the acceptance criteria of BLUI-5769?

**Review by JeffGreiner-eaton — APPROVED** [review]
looks good to me, examples covered. 

@ArshdeepSingh3-eaton can you update your channel value units & spacing example to include view style. see comments from this PR https://github.com/etn-ccis/blui-react-native/pull/27

**Comment by ArshdeepSingh3-eaton** [comment]
there is no styling added to the code
just a list of components

**Pull request merged**
