### PR TITLE
Added linting scripts for showcase

### PR DESCRIPTION
**Pull request by shubham-eaton**
#### Changes proposed in this Pull Request:

- Added linting script for showcase

#### To Test:

- yarn lint
- yarn lint:fix
- yarn showcase-lint
- yarn showcase-lint:fix

### CODE REVIEW

**Comment by ArshdeepSingh3-eaton** [comment]
still getting lint errors while running yarn showcase-lint

**Comment by shubham-eaton** [comment]
> still getting lint errors while running yarn showcase-lint

yarn showcase-lint will only show what are current lint errors. yarn showcase-lint:fix will fix the errors but it is limited to fixing only errors which is fixable to lint independently.

**Comment by jeffvg** [comment]
looks good

**Comment by ArshdeepSingh3-eaton** [comment]
shubham also add prettier scripts

**Comment by shubham-eaton** [comment]
> shubham also add prettier scripts

Added prettier scripts

**Review by surajeaton — APPROVED** [review]
Looks good.

**Pull request merged**
